export {
  DESKTOP_MAX_JSON_BYTES,
  DESKTOP_MAX_JSON_DEPTH,
  DESKTOP_MAX_JSON_NODES,
  DESKTOP_MAX_STAFF_DIRECTORY_SIZE,
  DESKTOP_OPERATION_SCHEMAS,
  DesktopCommandExecuteInputSchema,
  DesktopCommandExecuteResultSchema,
  DesktopCommandNameSchema,
  DesktopHealthGetInputSchema,
  DesktopHealthGetResultSchema,
  DesktopLoginInputSchema,
  DesktopLoginResultSchema,
  DesktopLogoutInputSchema,
  DesktopLogoutResultSchema,
  DesktopPinChallengeInputSchema,
  DesktopPinChallengeResultSchema,
  DesktopPinVerifyInputSchema,
  DesktopPinVerifyResultSchema,
  DesktopOfflineResumeResultSchema,
  DesktopQueryExecuteInputSchema,
  DesktopQueryExecuteResultSchema,
  DesktopQueryNameSchema,
  DesktopRefreshInputSchema,
  DesktopRefreshResultSchema,
  DesktopSessionViewSchema,
  DesktopStaffDirectoryEntrySchema,
  DesktopStaffDirectorySchema,
} from "./operations.js";
export type {
  DesktopCommandExecuteInput,
  DesktopCommandExecuteResult,
  DesktopCommandName,
  DesktopHealthGetResult,
  DesktopLoginInput,
  DesktopLoginResult,
  DesktopLogoutResult,
  DesktopPinChallengeResult,
  DesktopPinVerifyResult,
  DesktopOfflineResumeResult,
  DesktopQueryExecuteInput,
  DesktopQueryExecuteResult,
  DesktopQueryName,
  DesktopRefreshResult,
  DesktopSessionView,
  DesktopStaffDirectoryEntry,
} from "./operations.js";
export {
  DesktopOfflineConflictSchema,
  DesktopOfflineResolveInputSchema,
  DesktopOfflineResolveResultSchema,
  DesktopOfflineResumeInputSchema,
  DesktopOfflineStatusInputSchema,
  DesktopOfflineStatusResultSchema,
} from "./offline-operations.js";
export type {
  DesktopOfflineConflict,
  DesktopOfflineResolveInput,
  DesktopOfflineStatusResult,
} from "./offline-operations.js";
export {
  DESKTOP_MAX_PHOTO_BYTES,
  DesktopPhotoDeleteInputSchema,
  DesktopPhotoDeleteResultSchema,
  DesktopPhotoReadInputSchema,
  DesktopPhotoReadResultSchema,
  DesktopPhotoUploadInputSchema,
  DesktopPhotoUploadResultSchema,
} from "./photo-operations.js";
export type {
  DesktopPhotoDeleteInput,
  DesktopPhotoDeleteResult,
  DesktopPhotoReadInput,
  DesktopPhotoReadResult,
  DesktopPhotoUploadInput,
  DesktopPhotoUploadResult,
} from "./photo-operations.js";
