packages:
  - "apps/*"
  - "packages/*"
  - "tools/*"

overrides:
  find-my-way: 9.7.0

allowBuilds:
  "@google/genai": false
  better-sqlite3: true
  electron: true
  electron-winstaller: false
  esbuild: true
  protobufjs: true
