import type { AccountingHandlerDeps } from "../accounting/types.js";
import type { ChainPortHooks } from "../bus/chain-adapter.js";
import type { MutableCommandRegistry } from "../bus/registry.js";
import type { MutableQueryRegistry } from "../bus/query-registry.js";
import type { CatalogHandlerDeps } from "../catalog/handlers.js";
import type { CustomerProfileHandlerDeps } from "../customer-profile/handlers.js";
import type { CustomerHandlerDeps } from "../customer/handlers.js";
import type { DeliveryPolicyHandlerDeps } from "../delivery-policy/handlers.js";
import type { FulfillmentHandlerDeps } from "../fulfillment/handlers.js";
import type { MemberBenefitsRuntimeDeps } from "../member-benefits/types.js";
import type { MemberRuntimeDeps } from "../member/handlers.js";
import type { NotificationHandlerDeps } from "../notification/types.js";
import type { OrderHandlerDeps } from "../order/handlers.js";
import type { PhotoHandlerDeps } from "../photo/handlers.js";
import type { PricingHandlerDeps } from "../pricing/handlers.js";
import type { PrintHandlerDeps } from "../print/handlers.js";
import type { ReconciliationHandlerDeps } from "../reconciliation/types.js";
import type { ReportingHandlerDeps } from "../reporting/types.js";
import type { ShiftHandlerDeps } from "../shift/handlers.js";
import type { StaffAccessHandlerDeps } from "../staff/handlers.js";
import type { StoreManagementHandlerDeps } from "../store-management/types.js";
import type { StatsHandlerDeps } from "../stats/handlers.js";
import type { IdentityHandlerDeps } from "./identity-handlers.js";
import type { PlatformHandlerDeps } from "./platform-handlers.js";

export type RegisterM1Deps = Readonly<{
  identity?: IdentityHandlerDeps;
  platform?: PlatformHandlerDeps;
  pricing?: PricingHandlerDeps;
  deliveryPolicy?: DeliveryPolicyHandlerDeps;
  order?: OrderHandlerDeps;
  catalog?: CatalogHandlerDeps;
  print?: PrintHandlerDeps;
  stats?: StatsHandlerDeps;
  customer?: CustomerHandlerDeps;
  customerProfile?: CustomerProfileHandlerDeps;
  shift?: ShiftHandlerDeps;
  reconciliation?: ReconciliationHandlerDeps;
  accounting?: AccountingHandlerDeps;
  reporting?: ReportingHandlerDeps;
  photo?: PhotoHandlerDeps;
  fulfillment?: FulfillmentHandlerDeps;
  staffAccess?: StaffAccessHandlerDeps;
  storeManagement?: StoreManagementHandlerDeps;
  member?: MemberRuntimeDeps;
  memberBenefits?: MemberBenefitsRuntimeDeps;
  notification?: NotificationHandlerDeps;
}>;

export type RegisterM1Result = Readonly<{
  registry: MutableCommandRegistry;
  queryRegistry: MutableQueryRegistry;
  chainHooks: ChainPortHooks;
  registered: readonly string[];
  registeredQueries: readonly string[];
}>;
