import type { CommandDefinition, QueryDefinition } from "../registry/definitions.js";
import type { z } from "zod";
import {
  M2_CONTRACT_COMMAND_NAMES as BASE_COMMAND_NAMES,
  M2_CONTRACT_DEFINITIONS as BASE_DEFINITIONS,
  M2_CONTRACT_QUERY_NAMES as BASE_QUERY_NAMES,
  M2_SKELETON_COMMAND_NAMES as BASE_SKELETON_COMMAND_NAMES,
  M2_SKELETON_DEFINITIONS as BASE_SKELETON_DEFINITIONS,
} from "./catalog-base.js";
import {
  DELIVERY_POLICY_COMMAND_NAMES,
  DELIVERY_POLICY_COMMANDS,
  DELIVERY_POLICY_QUERIES,
  DELIVERY_POLICY_QUERY_NAMES,
} from "./delivery-policy.js";
import {
  DELIVERY_APPOINTMENT_COMMAND_NAMES,
  DELIVERY_APPOINTMENT_COMMANDS,
  DELIVERY_APPOINTMENT_QUERIES,
  DELIVERY_APPOINTMENT_QUERY_NAMES,
} from "./delivery-appointments.js";
import {
  DELIVERY_ORDER_COMMAND_NAMES,
  DELIVERY_ORDER_COMMANDS,
  DELIVERY_ORDER_QUERIES,
  DELIVERY_ORDER_QUERY_NAMES,
} from "./delivery-orders.js";
import {
  DELIVERY_TASK_COMMAND_NAMES,
  DELIVERY_TASK_COMMANDS,
  DELIVERY_TASK_QUERIES,
  DELIVERY_TASK_QUERY_NAMES,
} from "./delivery-tasks.js";
import {
  DELIVERY_EVIDENCE_COMMAND_NAMES,
  DELIVERY_EVIDENCE_COMMANDS,
  DELIVERY_EVIDENCE_QUERIES,
  DELIVERY_EVIDENCE_QUERY_NAMES,
} from "./delivery-evidence.js";
import {
  CUSTOMER_SELF_SERVICE_QUERIES,
  CUSTOMER_SELF_SERVICE_QUERY_NAMES,
} from "./customer-self-service.js";
import {
  MARKETING_COMMAND_NAMES,
  MARKETING_COMMANDS,
  MARKETING_QUERIES,
  MARKETING_QUERY_NAMES,
} from "./marketing.js";
import {
  MARKETING_COUPON_COMMAND_NAMES,
  MARKETING_COUPON_COMMANDS,
  MARKETING_COUPON_QUERIES,
  MARKETING_COUPON_QUERY_NAMES,
} from "./marketing-coupons.js";
import {
  MARKETING_EXTENSION_COMMAND_NAMES,
  MARKETING_EXTENSION_COMMANDS,
} from "./marketing-extensions.js";

export * from "./catalog-base.js";

/** ADR-46 through ADR-51 extend the frozen surface while keeping the historical catalog bounded. */
export const M2_SKELETON_DEFINITIONS: readonly CommandDefinition<z.ZodObject>[] = Object.freeze([
  ...BASE_SKELETON_DEFINITIONS,
  ...DELIVERY_POLICY_COMMANDS,
  ...DELIVERY_APPOINTMENT_COMMANDS,
  ...DELIVERY_ORDER_COMMANDS,
  ...DELIVERY_TASK_COMMANDS,
  ...DELIVERY_EVIDENCE_COMMANDS,
  ...MARKETING_COMMANDS,
  ...MARKETING_COUPON_COMMANDS,
  ...MARKETING_EXTENSION_COMMANDS,
]);

export const M2_SKELETON_COMMAND_NAMES = Object.freeze([
  ...BASE_SKELETON_COMMAND_NAMES,
  ...DELIVERY_POLICY_COMMAND_NAMES,
  ...DELIVERY_APPOINTMENT_COMMAND_NAMES,
  ...DELIVERY_ORDER_COMMAND_NAMES,
  ...DELIVERY_TASK_COMMAND_NAMES,
  ...DELIVERY_EVIDENCE_COMMAND_NAMES,
  ...MARKETING_COMMAND_NAMES,
  ...MARKETING_COUPON_COMMAND_NAMES,
  ...MARKETING_EXTENSION_COMMAND_NAMES,
] as const);

export const M2_CONTRACT_COMMAND_NAMES = Object.freeze([
  ...BASE_COMMAND_NAMES,
  ...DELIVERY_POLICY_COMMAND_NAMES,
  ...DELIVERY_APPOINTMENT_COMMAND_NAMES,
  ...DELIVERY_ORDER_COMMAND_NAMES,
  ...DELIVERY_TASK_COMMAND_NAMES,
  ...DELIVERY_EVIDENCE_COMMAND_NAMES,
  ...MARKETING_COMMAND_NAMES,
  ...MARKETING_COUPON_COMMAND_NAMES,
  ...MARKETING_EXTENSION_COMMAND_NAMES,
] as const);

export const M2_CONTRACT_QUERY_NAMES = Object.freeze([
  ...BASE_QUERY_NAMES,
  ...DELIVERY_POLICY_QUERY_NAMES,
  ...DELIVERY_APPOINTMENT_QUERY_NAMES,
  ...DELIVERY_ORDER_QUERY_NAMES,
  ...DELIVERY_TASK_QUERY_NAMES,
  ...DELIVERY_EVIDENCE_QUERY_NAMES,
  ...MARKETING_QUERY_NAMES,
  ...MARKETING_COUPON_QUERY_NAMES,
  ...CUSTOMER_SELF_SERVICE_QUERY_NAMES,
] as const);

export const M2_CONTRACT_DEFINITIONS: readonly (
  CommandDefinition<z.ZodObject> | QueryDefinition<z.ZodObject>
)[] = Object.freeze([
  ...BASE_DEFINITIONS,
  ...DELIVERY_POLICY_COMMANDS,
  ...DELIVERY_POLICY_QUERIES,
  ...DELIVERY_APPOINTMENT_COMMANDS,
  ...DELIVERY_APPOINTMENT_QUERIES,
  ...DELIVERY_ORDER_COMMANDS,
  ...DELIVERY_ORDER_QUERIES,
  ...DELIVERY_TASK_COMMANDS,
  ...DELIVERY_TASK_QUERIES,
  ...DELIVERY_EVIDENCE_COMMANDS,
  ...DELIVERY_EVIDENCE_QUERIES,
  ...MARKETING_COMMANDS,
  ...MARKETING_QUERIES,
  ...MARKETING_COUPON_COMMANDS,
  ...MARKETING_COUPON_QUERIES,
  ...MARKETING_EXTENSION_COMMANDS,
  ...CUSTOMER_SELF_SERVICE_QUERIES,
]);
