#!/usr/bin/env bash
# Apply formal @laundry/db SQL migrations against local tools/compose Postgres.
# LOCAL ONLY — not invoked by CI. Requires Docker Compose postgres (or host psql).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
MIGRATIONS_DIR="${REPO_ROOT}/packages/db/src/migrations"
POSTGRES_CONTAINER="${POSTGRES_CONTAINER:-laundry-postgres-spike}"

# ---------------------------------------------------------------------------
# Connection defaults match tools/compose (LOCAL ONLY weak credentials)
# Prefer LAUNDRY_OWNER_DATABASE_URL, then DATABASE_URL, then compose owner URL.
# ---------------------------------------------------------------------------
PGHOST="${PGHOST:-127.0.0.1}"
PGPORT="${PGPORT:-8543}"
PGDATABASE="${PGDATABASE:-laundry_v2}"
LAUNDRY_OWNER_USER="${LAUNDRY_OWNER_USER:-laundry_owner}"
LAUNDRY_OWNER_PASSWORD="${LAUNDRY_OWNER_PASSWORD:-owner_secure_password}"
POSTGRES_USER="${POSTGRES_USER:-postgres}"
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-postgres_secure_password}"

DEFAULT_OWNER_URL="postgresql://${LAUNDRY_OWNER_USER}:${LAUNDRY_OWNER_PASSWORD}@${PGHOST}:${PGPORT}/${PGDATABASE}"
DEFAULT_SUPERUSER_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${PGHOST}:${PGPORT}/${PGDATABASE}"

DATABASE_URL="${LAUNDRY_OWNER_DATABASE_URL:-${DATABASE_URL:-${DEFAULT_OWNER_URL}}}"
SUPERUSER_DATABASE_URL="${SUPERUSER_DATABASE_URL:-${DEFAULT_SUPERUSER_URL}}"

MIGRATION_FILES=(
  "0001_roles.sql"
  "0002_m1_identity_platform.sql"
  "0003_rls_and_grants.sql"
)

die() {
  echo "❌ [migrate-v2] $*" >&2
  exit 1
}

log() {
  echo "=== [migrate-v2] $* ==="
}

require_migration_files() {
  local file
  [[ -d "${MIGRATIONS_DIR}" ]] || die "migrations dir missing: ${MIGRATIONS_DIR}"
  for file in "${MIGRATION_FILES[@]}"; do
    [[ -f "${MIGRATIONS_DIR}/${file}" ]] || die "missing migration: ${MIGRATIONS_DIR}/${file}"
  done
}

# Build one SQL stream: roles first, then SET ROLE owner for table ownership, then schema/RLS.
# Single session so 0001's ALTER ROLE ... NOLOGIN does not block later files in the same run.
build_sql_bundle() {
  local file
  echo "-- laundry-desk formal packages/db migrations (expand-only)"
  echo "-- generated by tools/compose/migrate-v2.sh"
  echo
  echo "-- >>> ${MIGRATION_FILES[0]}"
  cat "${MIGRATIONS_DIR}/${MIGRATION_FILES[0]}"
  echo
  # Ensure subsequent DDL is owned by laundry_owner when connected as superuser.
  # No-op when already connected as laundry_owner.
  echo "SET ROLE laundry_owner;"
  echo
  for file in "${MIGRATION_FILES[@]:1}"; do
    echo "-- >>> ${file}"
    cat "${MIGRATIONS_DIR}/${file}"
    echo
  done
}

container_running() {
  docker inspect -f '{{.State.Running}}' "${POSTGRES_CONTAINER}" 2>/dev/null | grep -qx true
}

run_psql_url() {
  local url="$1"
  command -v psql >/dev/null 2>&1 || return 1
  build_sql_bundle | psql "${url}" -v ON_ERROR_STOP=1 -X -q
}

run_psql_docker() {
  local user="$1"
  container_running || return 1
  build_sql_bundle | docker exec -i \
    -e PGPASSWORD \
    "${POSTGRES_CONTAINER}" \
    psql -U "${user}" -d "${PGDATABASE}" -v ON_ERROR_STOP=1 -X -q
}

apply_migrations() {
  log "Applying formal migrations from packages/db/src/migrations"
  echo "    target migrations: ${MIGRATION_FILES[*]}"
  echo "    DATABASE_URL host defaults: ${PGHOST}:${PGPORT}/${PGDATABASE} (user=laundry_owner preferred)"

  if command -v psql >/dev/null 2>&1; then
    if run_psql_url "${DATABASE_URL}"; then
      log "Applied via host psql (owner/DATABASE_URL)"
      return 0
    fi
    echo "⚠ owner/DATABASE_URL connection failed; retrying as compose superuser (SET ROLE laundry_owner in bundle)"
    if run_psql_url "${SUPERUSER_DATABASE_URL}"; then
      log "Applied via host psql (postgres superuser + SET ROLE laundry_owner)"
      return 0
    fi
    die "host psql could not apply migrations (owner and superuser URLs both failed)"
  fi

  if container_running; then
    if PGPASSWORD="${LAUNDRY_OWNER_PASSWORD}" run_psql_docker "${LAUNDRY_OWNER_USER}"; then
      log "Applied via docker exec as ${LAUNDRY_OWNER_USER} (${POSTGRES_CONTAINER})"
      return 0
    fi
    echo "⚠ docker exec as laundry_owner failed (role may be NOLOGIN after a prior migrate); retrying as postgres"
    if PGPASSWORD="${POSTGRES_PASSWORD}" run_psql_docker "${POSTGRES_USER}"; then
      log "Applied via docker exec as ${POSTGRES_USER} + SET ROLE laundry_owner"
      return 0
    fi
    die "docker exec could not apply migrations"
  fi

  die "neither host psql nor running container '${POSTGRES_CONTAINER}' is available.
Start local compose first:
  cd tools/compose && docker compose up -d postgres
Then re-run:
  ./tools/compose/migrate-v2.sh"
}

require_migration_files
apply_migrations
log "OK — formal packages/db migrations applied (0001 → 0003)"
