import type { CsrfProofSigner } from "../auth/csrf.js";
import type { AccountingHandlerDeps } from "../accounting/types.js";
import type { CommandIdempotencyStore, StepUpApproverAuthority } from "../bus/types.js";
import type { CatalogHandlerDeps } from "../catalog/handlers.js";
import type { CustomerHandlerDeps } from "../customer/handlers.js";
import type { CustomerProfileHandlerDeps } from "../customer-profile/handlers.js";
import type { CreatePoolOptions, PgPool } from "../db/pg-pool.js";
import type { EdgeAuthorityService } from "../edge/authority-service.js";
import type { FulfillmentHandlerDeps } from "../fulfillment/handlers.js";
import type { IdentityHandlerDeps } from "../handlers/identity-handlers.js";
import type { createMemoryIdentityStore } from "../identity/memory-store.js";
import type { MemberRuntimeDeps } from "../member/handlers.js";
import type { MemberBenefitsRuntimeDeps } from "../member-benefits/types.js";
import type { MarketingHandlerDeps } from "../marketing/types.js";
import type { NotificationHandlerDeps } from "../notification/types.js";
import type { OrderHandlerDeps } from "../order/handlers.js";
import type { PendingActionStore } from "../pending-actions/types.js";
import type { PhotoHandlerDeps } from "../photo/handlers.js";
import type { StepUpProofStore } from "../policy/step-up-proof-store.js";
import type { PrintHandlerDeps } from "../print/handlers.js";
import type { PrintDispatchService } from "../print/dispatch-service.js";
import type { ReconciliationHandlerDeps } from "../reconciliation/types.js";
import type { ReportingHandlerDeps } from "../reporting/types.js";
import type { ShiftHandlerDeps } from "../shift/handlers.js";
import type { StaffAccessHandlerDeps } from "../staff/handlers.js";
import type { StoreManagementHandlerDeps } from "../store-management/types.js";
import type { StatsHandlerDeps } from "../stats/handlers.js";
import type { PlatformHandlerDeps } from "../platform/handlers.js";
import type { PricingHandlerDeps } from "../pricing/handlers.js";
import type { LocalStaffDirectoryEntry } from "./staff-directory.js";

export type LocalRuntimeMode = "memory" | "pg";

export type CreatePgLocalRuntimeDependencies = Readonly<{
  createPool: (options: CreatePoolOptions) => PgPool;
  assertReady: (pool: PgPool, expectedDemoOnly: boolean) => Promise<void>;
  loadStaffDirectory: (pool: PgPool) => Promise<readonly LocalStaffDirectoryEntry[]>;
}>;

export type LocalRuntime = Readonly<{
  mode: LocalRuntimeMode;
  identity: IdentityHandlerDeps;
  platform: PlatformHandlerDeps;
  pricing: PricingHandlerDeps;
  order: OrderHandlerDeps;
  catalog: CatalogHandlerDeps;
  print: PrintHandlerDeps;
  /** Main-process-only signed Edge print transport; absent from memory diagnostics. */
  printDispatch: PrintDispatchService | null;
  stats: StatsHandlerDeps;
  customer: CustomerHandlerDeps;
  customerProfile: CustomerProfileHandlerDeps;
  shift: ShiftHandlerDeps;
  reconciliation: ReconciliationHandlerDeps;
  accounting: AccountingHandlerDeps;
  reporting: ReportingHandlerDeps;
  photo: PhotoHandlerDeps;
  fulfillment: FulfillmentHandlerDeps;
  staffAccess: StaffAccessHandlerDeps;
  storeManagement: StoreManagementHandlerDeps;
  member: MemberRuntimeDeps;
  memberBenefits: MemberBenefitsRuntimeDeps;
  notification: NotificationHandlerDeps;
  marketing: MarketingHandlerDeps;
  edgeAuthority: EdgeAuthorityService;
  accessTokenSecret: string;
  csrfProofSigner: CsrfProofSigner;
  staffDirectory: readonly LocalStaffDirectoryEntry[];
  pendingStore: PendingActionStore;
  stepUpProofStore: StepUpProofStore;
  stepUpApproverAuthority: StepUpApproverAuthority;
  idempotencyStore: CommandIdempotencyStore;
  pool: PgPool | null;
  store: ReturnType<typeof createMemoryIdentityStore> | null;
}>;
